### ISSUE TITLE
emacs s***s

### ISSUE THREAD

**Issue by salc2** [LaurenceWarne/.emacs.d#1]
I just wanted to capture your attention xD
(still VIM rules)
Anyway I know it's kind of late notice but if you are around Manchester city centre to night pop up in the Disney Streaming meetup ->  https://www.meetup.com/disney-streaming-technology-manchester/events/284022777/
There is going to be some talks about weapon X and cxe and pizza.
Hope you can make it.
Cheers.

**Comment by LaurenceWarne** [comment]
> I just wanted to capture your attention xD

:laughing: 

> emacs s***s

Some lines you just can't cross.

Oh cool, I don't think I can make it tonight but I've joined the group - promise I'll be at the next one :slightly_smiling_face:

 Anyway, I hope you're well :slightly_smiling_face:

**Comment by salc2** [comment]
with that said, I can close the issue, no more concerns with emacs it's OKish lol.

yeah I am good thanks, hope everything is fine over there also.

see you around 👋

**Comment by LaurenceWarne** [comment]
@salc2 what's your email btw? I tried *** but it's telling me the address is not found :smile:

**Comment by salc2** [comment]
hey, yeah you are missing a "r".
It's ***@***.***
You should open a LinkedIn if have not done it yet xD

**Comment by LaurenceWarne** [comment]
> hey, yeah you are missing a "r".

I should have noticed that, I think it's wrong on your profile (possibly also on your git commits?)

> You should open a LinkedIn if have not done it yet xD

I've done it, should have done it sooner, too much of a troglodyte :smile:
